// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeWK9A50T2u-DPfhLbQUn9vKaWdddiH_4',
    appId: '1:467920361410:web:7b1495b8836c16c3fb685b',
    messagingSenderId: '467920361410',
    projectId: 'js-goods-daa16',
    authDomain: 'js-goods-daa16.firebaseapp.com',
    storageBucket: 'js-goods-daa16.appspot.com',
    measurementId: 'G-37LE5X166N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe2B6ggBvgW9ryocW3iCza7ia12woNXJ0',
    appId: '1:467920361410:android:a8434d41f9b7060efb685b',
    messagingSenderId: '467920361410',
    projectId: 'js-goods-daa16',
    storageBucket: 'js-goods-daa16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACYxdhI2KqLDUDIYp4W0Hr3PwmngznQdM',
    appId: '1:467920361410:ios:e6e0e3b248c8f27bfb685b',
    messagingSenderId: '467920361410',
    projectId: 'js-goods-daa16',
    storageBucket: 'js-goods-daa16.appspot.com',
    androidClientId: '467920361410-deosss9h18d5ljkpja8tqfmqk8cuarh2.apps.googleusercontent.com',
    iosClientId: '467920361410-6tsmuvl0441n9g6hnn4mspbnv54uh1sq.apps.googleusercontent.com',
    iosBundleId: 'com.example.jsGoods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACYxdhI2KqLDUDIYp4W0Hr3PwmngznQdM',
    appId: '1:467920361410:ios:236b68428dba9b01fb685b',
    messagingSenderId: '467920361410',
    projectId: 'js-goods-daa16',
    storageBucket: 'js-goods-daa16.appspot.com',
    androidClientId: '467920361410-deosss9h18d5ljkpja8tqfmqk8cuarh2.apps.googleusercontent.com',
    iosClientId: '467920361410-b9900r74lmrk6713vgguq41rp9luscf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.jsGoods.RunnerTests',
  );
}
